apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-configuracao
          image: haaragard/app-variaveis-ambiente:v1
          ports:
            - containerPort: 8080
          envFrom:
#            - configMapRef:
#                name: app-config
            - secretRef:
                name: app-secret
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app-config
# data:
#   APP_NAME: "Aplicação ConfigMap"
#   APP_VERSION: "v4.0"
#   APP_AUTHOR: "Diogo Antunes"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_NAME: "QXBsaWNhw6fDo28gU2VjcmV0" # APP_NAME="Aplicação Secret"
  APP_VERSION: "djUuMA==" # APP_VERSION="v5.0"
  APP_AUTHOR: "RGlvZ28gQW50dW5lcyAtLVNlY3JldC0t" # APP_AUTHOR="Diogo Antunes --Secret--"
---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000